version: "3.1"

services:
  
  nginx:
    image: dagman62/nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - elk

  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044

